right_format = "$time "

palette = "catppuccin_mocha"

# Theming

[palettes.dracula]

background="#282A36"
foreground="#F8F8F2"
selection="#44475A"
comment="#6272A4"
red="#FF5555"
orange="#FFB86C"
yellow="#F1FA8C"
green="#50FA7B"
purple="#BD93F9"
cyan="#8BE9FD"
pink="#FF79C6"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Layout
 
[time]
disabled = false
format = '[$time]($style)'
time_format = "%H:%M"
