[target]
exclude = ['plugin/**', '.luarc.json']
require_empty = false

[target.windows]
exclude = []
directory = '~/AppData/Local/nvim'

[target.linux]
exclude = []
directory = '~/.config/nvim'

[dependencies.simple]
local = []
system = []
